target 'ddudda' do
  # ... existing code ...
  
  # React Native Maps dependencies
  # pod 'react-native-maps', path: '../node_modules/react-native-maps'
  
  # React Native WebView dependencies
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # ... existing code ...
end

# 스크립트 추가
post_install do |installer|
  # ... existing code ...
  
  # ATS 설정 추가
  ats_settings = {
    'NSAllowsArbitraryLoads' => true
  }
  
  project_path = installer.pods_project.path.to_path
  project_dir = File.dirname(project_path)
  target_name = 'ddudda'
  plist_path = "#{project_dir}/../#{target_name}/Info.plist"
  
  if File.exist?(plist_path)
    plist = Xcodeproj::Plist.read_from_path(plist_path)
    plist['NSAppTransportSecurity'] = ats_settings
    Xcodeproj::Plist.write_to_path(plist, plist_path)
    puts "Updated #{plist_path} with ATS settings"
  else
    puts "Could not find Info.plist at #{plist_path}"
  end
end 